Error: JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
This reverts commit f4c4a74d5bed4d02fb0cf11cc368ea3f67b802d6.